name: tekartik_io_auth_utils
description: helper for google auth for io app
version: 0.3.2
homepage: https://github.com/tekartik/io_auth_utils.dart

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  googleapis_auth: any
  fs_shim: any
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart2_3
    version: '>=0.7.0-0'
  yaml:
  path:
  http:
dev_dependencies:
  test: ">=1.0.0"
  dev_test: '>=0.13.3+12'
  googleapis: any
  process_run: '>=0.10.0+1'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'