name: tekartik_io_auth_utils
description: helper for google auth for io app
version: 0.3.2+1
homepage: https://github.com/tekartik/io_auth_utils.dart

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  googleapis: ">=1.2.0"
  googleapis_auth: ">=1.2.0"
  fs_shim: ">=2.3.3+1"
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart3a
    version: '>=0.7.0-0'
  yaml: ">=3.1.2"
  path: ">=1.9.0"
  http:
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
