name: tekartik_io_auth_utils
description: helper for google auth for io app
version: 0.3.0
homepage: https://github.com/tekartik/io_auth_utils.dart

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  googleapis_auth: any
  fs_shim: any
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: null_safety
    version: '>=0.7.0-0'
  yaml:
dev_dependencies:
  test: ">=1.0.0"
  dev_test: '>=0.13.3+12'
  googleapis: any
  process_run: '>=0.10.0+1'
  tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'